Repository RedHatQE/openshift-ci-job-trigger, pull requests merged in 2024-02, with the labels that each got.

#4 Update wait_for_job_completed logic
  openshift_ci_job_trigger/libs/job_triggering.py
Labels: verified, size/S, can-be-merged, branch-main, approved-myakove

#6 Add compose file
  docker-compose.yaml
Labels: verified, size/XS, needs-rebase, can-be-merged, branch-main, approved-rnetser

#9 Add log and change write data to file
  openshift_ci_job_trigger/libs/job_triggering.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove

#13 Use database instead of files
  openshift_ci_job_trigger/app.py
  openshift_ci_job_trigger/libs/job_db.py
  openshift_ci_job_trigger/libs/job_triggering.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/constants.py
  tests/manifests/openshift_ci_triggered_jobs.json
  tests/test_job_triggering.py
  tests/test_junit_results.py
  tox.ini
Labels: verified, size/XXL, can-be-merged, branch-main, approved-myakove

#16 Add more checks for pre-commit
  .pre-commit-config.yaml
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#20 Report status in slack
  openshift_ci_job_trigger/libs/job_triggering.py
  openshift_ci_job_trigger/utils/general.py
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser
